$('.owl-carousel').owlcarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items3
        },
        1000:{
            items:5
        }
    }
})